spring:
  redis:
    host: 81.70.207.243
    port: 6379
    database: 0 #??0????
    jedis:
      pool:
        max-active: 8 #?????
        max-wait: 1ms
        max-idle: 4 #??????
        min-idle: 0 #??????
    password: Aa1076766987

  cache:
    redis:
      time-to-live: 180000 #??ms

server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
